<?php

$saints = array(
  array('title' => 'Никоди́м Тисманский, Румынский','title_genitive' => 'Никоди́ма Тисманского, Румынского'),
  array('title' => 'Алекса́ндр (в схиме Алекси́й) Невский','title_genitive' => 'Алекса́ндра Невского, в схиме Алекси́я Невского'),
  array('title' => 'Ави́в Едесский','title_genitive' => 'Ави́ва Едесского'),
  array('title' => 'Исаа́к Сирин, Ниневийский','title_genitive' => 'Исаа́ка Сирина, Ниневийского'),
  array('title' => 'Николай Кандауров','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Кандаурова</em></span>'),
  array('title' => 'Исаа́к Синайский','title_genitive' => 'Исаа́ка Синайского'),
  array('title' => 'Васи́лий (Эрекаев)','title_genitive' => 'Васи́лия <span style="font-size: 10pt;"><em>(Эрекаева)</em></span>'),
  array('title' => 'Палла́дий Александрийский','title_genitive' => 'Палла́дия Александрийского'),
  array('title' => 'Лев Оптинский','title_genitive' => 'Льва Оптинского'),
  array('title' => 'Павел Новый, Константинопольский','title_genitive' => 'Павла Нового (784), Константинопольского'),
  array('title' => 'Лавре́нтий Комельский','title_genitive' => 'Лавре́нтия Комельского'),
  array('title' => 'Меле́тий (Пигас), Александрийский','title_genitive' => 'Меле́тия (Пигаса), Александрийского'),
  array('title' => 'Павел Добромыслов, Рязанский','title_genitive' => 'Павла <span style="font-size: 10pt;"><em>Добромыслова</em></span>, Рязанского'),
  array('title' => 'Михаил Косухин','title_genitive' => 'Михаила <span style="font-size: 10pt;"><em>Косухина</em></span>'),
  array('title' => 'Дими́трий Овечкин','title_genitive' => 'Дими́трия <span style="font-size: 10pt;"><em>Овечкина</em></span>'),
  array('title' => 'Севастиа́н Римский, военачальник','title_genitive' => 'Севастиа́на Римского'),
  array('title' => 'Влади́мир Виноградов','title_genitive' => 'Влади́мира <span style="font-size: 10pt;"><em>Виноградова</em></span>'),
  array('title' => 'Васи́лий Соколов','title_genitive' => 'Васи́лия <span style="font-size: 10pt;"><em>Соколова</em></span>'),
  array('title' => 'Иорда́н Месукевийский, Грузинский','title_genitive' => 'Иорда́на Месукевийского, Грузинского'),
  array('title' => 'Петр Марков','title_genitive' => 'Петра́ <span style="font-size: 10pt;"><em>Маркова</em></span>'),
  array('title' => 'Се́ргий Валаамский','title_genitive' => 'Се́ргия Валаамского'),
  array('title' => 'Григо́рий Гаряев','title_genitive' => 'Григо́рия <span style="font-size: 10pt;"><em>Гаряева</em></span>'),
  array('title' => 'Асинкри́т','title_genitive' => 'Асинкри́та'),
  array('title' => 'Мо́кий Эмесский (Емисский)','title_genitive' => 'Мо́кия Эмесского (Емисского)'),
  array('title' => 'Симео́н Палестинский, Емесский','title_genitive' => 'Симео́на Палестинского, Емесского'),
  array('title' => 'Влади́мир Панькин','title_genitive' => 'Влади́мира <span style="font-size: 10pt;"><em>Панькина</em></span>'),
  array('title' => 'Петр Никомидийский','title_genitive' => 'Петра Никомидийского'),
  array('title' => 'Алекса́ндр Воздвиженский','title_genitive' => 'Алекса́ндра <span style="font-size: 10pt;"><em>Воздвиженского</em></span>'),
  array('title' => 'Марк Псково-Печерский','title_genitive' => 'Ма́рка Псково-Печерского'),
  array('title' => 'Фома́ Дамасский','title_genitive' => 'Фомы́ Дамасского'),
  array('title' => 'Иси́дор Пелусиот','title_genitive' => 'Иси́дора Пелусиотского'),
  array('title' => 'Лео́нтий Печерский, канонарх','title_genitive' => 'Лео́нтия, канонарха Печерского, в Дальних пещерах'),
  array('title' => 'Петр Антонов','title_genitive' => 'Петра <span style="font-size: 10pt;"><em>Антонова</em></span>'),
  array('title' => 'Иакисхо́л Керкирский','title_genitive' => 'Иакисхо́ла Керкирского'),
  array('title' => 'Иа́ков Сербский','title_genitive' => 'Иа́кова Сербского'),
  array('title' => 'Филимо́н Газский','title_genitive' => 'Филимо́на Газского'),
  array('title' => 'Иоа́нн Сиракузский','title_genitive' => 'Иоа́нна Сиракузского'),
  array('title' => 'Августи́н Аврелий, Иппонийский','title_genitive' => 'Августи́на Аврелия, Иппонийского'),
  array('title' => 'Дометиа́н Севастийский','title_genitive' => 'Дометиа́на Севастийского'),
  array('title' => 'Ио́сиф Хуций, Мохевский, Грузинский чудотворец','title_genitive' => 'Ио́сифа Хуция, Мохевского, Грузинского чудотворца'),
  array('title' => 'Васи́лий Бова','title_genitive' => 'Васи́лия <span style="font-size: 10pt;"><em>Бовы</em></span>'),
  array('title' => 'Се́ргий Стрельников','title_genitive' => 'Се́ргия <span style="font-size: 10pt;"><em>Стрельникова</em></span>'),
  array('title' => 'Лавре́нтий Калужский, Христа ради юродивый','title_genitive' => 'Лавре́нтия, Христа ради юродивого, Калужского'),
  array('title' => 'Диса́н Персидский','title_genitive' => 'Диса́на Персидского'),
  array('title' => 'Корни́лий Комельский','title_genitive' => 'Корни́лия, чудотворца Комельского'),
  array('title' => 'Васо́й Амморейский (Фригийский)','title_genitive' => 'Васо́я Амморейского (Фригийского)'),
  array('title' => 'Иоа́нн Державин','title_genitive' => 'Иоа́нна <span style="font-size: 10pt;"><em>Державина</em></span>'),
  array('title' => 'Па́пий Коринфский','title_genitive' => 'Па́пия Коринфского'),
  array('title' => 'Гамалии́л, иудейский законоучитель','title_genitive' => 'Гамалии́ла, иудейского законоучителя'),
  array('title' => 'Фео́дор Фессалоникийский','title_genitive' => 'Фео́дора Фессалоникийского'),
  array('title' => 'Иоа́нн-Влади́мир Сербский, князь','title_genitive' => 'Иоа́нна-Влади́мира, кн. Сербского'),
  array('title' => 'Ма́ртин Фивейский','title_genitive' => 'Ма́ртина Фивейского'),
  array('title' => 'Григо́рий Декаполит','title_genitive' => 'Григо́рия Декаполита'),
  array('title' => 'Афинодо́р, ученик прп. Пахомия Великого','title_genitive' => 'Афинодо́ра, ученика прп. Пахомия Великого'),
  array('title' => 'Иоа́нн (Максимович), Шанхайский, Сан-Францисский','title_genitive' => 'Иоа́нна (Максимо́вича), Шанхайского, Сан-Францисского'),
  array('title' => 'Иоа́нн Демидов','title_genitive' => 'Иоа́нна <span style="font-size: 10pt;"><em>Демидова</em></span>'),
  array('title' => 'Влади́мир Дамаскин','title_genitive' => 'Влади́мира <span style="font-size: 10pt;"><em>Дамаскина</em></span>'),
  array('title' => 'Ио́сиф Египетский, ученик прп. Анто́ния Великого','title_genitive' => 'Ио́сифа Египетского, ученика прп. Анто́ния Великого'),
  array('title' => 'Все́волод (в Крещении Гаврии́л) Новгородский, Псковский','title_genitive' => 'Все́волода, во Святом Крещении Гаврии́ла, Новгородского, Псковского'),
  array('title' => 'Васи́лий Покровский','title_genitive' => 'Васи́лия <span style="font-size: 10pt;"><em>Покровского</em></span>'),
  array('title' => 'Нил Столобе́нский','title_genitive' => 'Ни́ла Столобе́нского'),
  array('title' => 'Киприа́н (Кири́н, Кири́лл) Бастийский, Месопольский','title_genitive' => 'Киприа́на (Кири́на, Кири́лла) Бастийского, Месопольского'),
  array('title' => 'Михаил Абрамов','title_genitive' => 'Михаила <span style="font-size: 10pt;"><em>Абрамова</em></span>'),
  array('title' => 'Иоа́нн Румянцев','title_genitive' => 'Иоа́нна <span style="font-size: 10pt;"><em>Румянцева</em></span>'),
  array('title' => 'Виссарио́н Селинин','title_genitive' => 'Виссарио́на <span style="font-size: 10pt;"><em>Селинина</em></span>'),
  array('title' => 'Иско́й Готфский','title_genitive' => 'Иско́я Готфского'),
  array('title' => 'Ти́хон Медынский, Калужский','title_genitive' => 'Ти́хона Медынского, Калужского'),
  array('title' => 'Оси́я Кордувийский','title_genitive' => 'Оси́и Кордувийского'),
  array('title' => 'Евдокси́й Севастийский','title_genitive' => 'Евдокси́я Севастийского'),
  array('title' => 'Фео́дор Тивериопольский','title_genitive' => 'Фео́дора Тивериопольского'),
  array('title' => 'Иси́дор Римский','title_genitive' => 'Иси́дора Римского'),
  array('title' => 'Криске́нт Галатийский','title_genitive' => 'Криске́нта Галатийского'),
  array('title' => 'Кла́вдий Римский, трибун','title_genitive' => 'Кла́вдия Римского, трибуна'),
  array('title' => 'Га́ий Садонский, Анкирский','title_genitive' => 'Га́ия Садонского, Анкирского'),
  array('title' => 'Нердо́н','title_genitive' => 'Нердо́на'),
  array('title' => 'Иувенти́н (Евве́нтий) Антиохийский','title_genitive' => 'Евве́нтия (Иувенти́на) Антиохийского'),
  array('title' => 'Симео́н Кульгавец','title_genitive' => 'Симео́на <span style="font-size: 10pt;"><em>Кульгавца</em></span>'),
  array('title' => 'Стефа́н I Венгерский, король','title_genitive' => 'Стефа́на I, короля Венгрии'),
  array('title' => 'Марк Нитрийский, Египетский, Келлийский, Подвижник, Постник','title_genitive' => 'Ма́рка Нитрийского, Египетского, Келлийского, Подвижника, Постника'),
  array('title' => 'Евге́ний Вифинский','title_genitive' => 'Евге́ния Вифинского'),
  array('title' => 'Петр Троицкий','title_genitive' => 'Петра <span style="font-size: 10pt;"><em>Троицкого</em></span>'),
  array('title' => 'Алекси́й Тютюнов','title_genitive' => 'Алекси́я <span style="font-size: 10pt;"><em>Тютюнова</em></span>'),
  array('title' => 'Константин Сухов','title_genitive' => 'Константина <span style="font-size: 10pt;"><em>Сухова</em></span>'),
  array('title' => 'Матфи́й Рябцев','title_genitive' => 'Матфи́я Рябцева'),
  array('title' => 'Васи́лий Крылов','title_genitive' => 'Васи́лия <span style="font-size: 10pt;"><em>Крылова</em></span>'),
  array('title' => 'Ши́о Новый, Гареджийский','title_genitive' => 'Ши́о Нового, Гареджийского'),
  array('title' => 'Алекса́ндр Никольский','title_genitive' => 'Алекса́ндра <span style="font-size: 10pt;"><em>Никольского</em></span>'),
  array('title' => 'Антони́н Ефесский','title_genitive' => 'Антони́на Ефесского'),
  array('title' => 'Иоа́нн Монагрийский','title_genitive' => 'Иоа́нна Монагрийского'),
  array('title' => 'Гермоге́н (Долганев), Тобольский','title_genitive' => 'Гермоге́на <span style="font-size: 10pt;"><em>(Долганева)</em></span>, Тобольского'),
  array('title' => 'Мена́ндр Прусский (Вифинский)','title_genitive' => 'Мена́ндра Прусского (Вифинского)'),
  array('title' => 'Ага́пий Едесский','title_genitive' => 'Ага́пия Едесского'),
  array('title' => 'Диони́сий Валаамский','title_genitive' => 'Диони́сия Валаамского'),
  array('title' => 'Иоа́нн Косинский','title_genitive' => 'Иоа́нна <span style="font-size: 10pt;"><em>Косинского</em></span>'),
  array('title' => 'Гео́ргий Коссов','title_genitive' => 'Гео́ргия <span style="font-size: 10pt;"><em>Коссова</em></span>'),
  array('title' => 'Пахо́мий Русский, Афонский','title_genitive' => 'Пахо́мия Русского, Афонского'),
  array('title' => 'Иа́ков Боровичский, Новгородский','title_genitive' => 'Иа́кова Боровичского, Новгородского'),
  array('title' => 'Николай Сафонов','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Сафонова</em></span>'),
  array('title' => 'Домн Севастийский','title_genitive' => 'До́мна Севастийского'),
  array('title' => 'Петр Влахернский','title_genitive' => 'Петра Влахернского'),
  array('title' => 'Никола́й Постников','title_genitive' => 'Никола́я <span style="font-size: 10pt;"><em>Постникова</em></span>'),
  array('title' => 'Флоре́нтий Нурсийский, Италийский, Фолиньосский','title_genitive' => 'Флоре́нтия'),
  array('title' => 'Дими́трий Миловидов','title_genitive' => 'Дими́трия <span style="font-size: 10pt;"><em>Миловидова</em></span>'),
  array('title' => 'Примити́в','title_genitive' => 'Примити́ва'),
  array('title' => 'Кирилл Белый, Новоезерский (Новгородский)','title_genitive' => 'Кирилла Новоезерского (Новгородского)'),
  array('title' => 'Николай Магнезийский','title_genitive' => 'Николая Магнезийского'),
  array('title' => 'Афинодо́р Амасийский','title_genitive' => 'Афинодо́ра Амасийского'),
  array('title' => 'Влади́мир Введенский','title_genitive' => 'Влади́мира <span style="font-size: 10pt;"><em>Введенского</em></span>'),
  array('title' => 'Фану́рий Родосский','title_genitive' => 'Фану́рия Родосского'),
  array('title' => 'Се́ргий Кедров','title_genitive' => 'Се́ргия <span style="font-size: 10pt;"><em>Кедрова</em></span>'),
  array('title' => 'Роми́л Римский','title_genitive' => 'Роми́ла Римского'),
  array('title' => 'Амфило́хий Печерский, Владимиро-Волынский','title_genitive' => 'Амфило́хия Печерского'),
  array('title' => 'Евстра́тий Печерский','title_genitive' => 'Евстра́тия Печерского, в Ближних пещерах'),
  array('title' => 'Исмаи́л Базилевский','title_genitive' => 'Исмаи́ла <span style="font-size: 10pt;"><em>Базилевского</em></span>'),
  array('title' => 'Дави́д Ярославский','title_genitive' => 'Дави́да'),
  array('title' => 'Ор Сирмийский','title_genitive' => 'Ора Сирмийского'),
  array('title' => 'Васи́лий Крылов','title_genitive' => 'Васи́лия <span style="font-size: 10pt;"><em>Крылова</em></span>'),
  array('title' => 'Николай (Ащепьев)','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>(Ащепьева)</em></span>'),
  array('title' => 'Варлаа́м Тобольский','title_genitive' => 'Варлаа́ма'),
  array('title' => 'Тимофе́й Петропавловский','title_genitive' => 'Тимофе́я <span style="font-size: 10pt;"><em>Петропавловского</em></span>'),
  array('title' => 'Стефа́н Триглийский','title_genitive' => 'Стефа́на чудотворца, исп.'),
  array('title' => 'Стефа́н Хирсский','title_genitive' => 'Стефа́на Хирсского'),
  array('title' => 'Гора́зд Охридский','title_genitive' => 'Гора́зда'),
  array('title' => 'Дави́д Ермопольский','title_genitive' => 'Дави́да Ермопольского'),
  array('title' => 'Васи́лий Виноградов','title_genitive' => 'Васи́лия <span style="font-size: 10pt;"><em>Виноградова</em></span>'),
  array('title' => 'Алекси́й Кротенков','title_genitive' => 'Алекси́я <span style="font-size: 10pt;"><em>Кротенкова</em></span>'),
  array('title' => 'Ипа́тий Руфианский','title_genitive' => 'Ипа́тия Руфианского'),
  array('title' => 'Фео́фил Закинфский','title_genitive' => 'Фео́фила Закинфского'),
  array('title' => 'Феофа́н (Ильминский), Соликамский','title_genitive' => 'Феофа́на <span style="font-size: 10pt;"><em>(Ильминского)</em></span>'),
  array('title' => 'Мира́кс Египтянин','title_genitive' => 'Мира́кса Египтянина'),
  array('title' => 'Си́мон Зографский (Афонский)','title_genitive' => 'Си́мона'),
  array('title' => 'Зино́н Веронийский','title_genitive' => 'Зино́на Веронийского'),
  array('title' => 'Иларио́н (Писарец)','title_genitive' => 'Иларио́на <span style="font-size: 10pt;"><em>(Писарца)</em></span>'),
  array('title' => 'Феопе́мпт Никомидийский','title_genitive' => 'Феопе́мпта'),
  array('title' => 'Ага́пий Каппадокийский','title_genitive' => 'Ага́пия Каппадокийского'),
  array('title' => 'Михаил Вознесенский','title_genitive' => 'Михаила <span style="font-size: 10pt;"><em>Вознесенского</em></span>'),
  array('title' => 'Влади́мир Зубкович','title_genitive' => 'Влади́мира <span style="font-size: 10pt;"><em>Зубковича</em></span>'),
  array('title' => 'Стефа́н, первомученик','title_genitive' => 'Стефа́на'),
  array('title' => 'Вячесла́в (Косожилин), Белогорский','title_genitive' => 'Вячесла́ва <span style="font-size: 10pt;"><em>(Косожилина)</em></span>'),
  array('title' => 'Николай Варжанский','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Варжанского</em></span>'),
  array('title' => 'Иоа́нн Виленский (Литовский)','title_genitive' => 'Иоа́нна'),
  array('title' => 'Ти́хик Колофонский','title_genitive' => 'Ти́хика'),
  array('title' => 'Иоа́нн Шишев','title_genitive' => 'Иоа́нна <span style="font-size: 10pt;"><em>Шишева</em></span>'),
  array('title' => 'Анаста́сий Месукевийский, Грузинский','title_genitive' => 'Анаста́сия'),
  array('title' => 'Фео́дор Антипин','title_genitive' => 'Фео́дора <span style="font-size: 10pt;"><em>Антипина</em></span>'),
  array('title' => 'Николай Амассийский','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Амассийского</em></span>'),
  array('title' => 'Вакх Новый','title_genitive' => 'Ва́кха Нового'),
  array('title' => 'Алекса́ндр Буравцев','title_genitive' => 'Алекса́ндра <span style="font-size: 10pt;"><em>Буравцева</em></span>'),
  array('title' => 'Алекси́й Горбачев','title_genitive' => 'Алекси́я <span style="font-size: 10pt;"><em>Горбачева</em></span>'),
  array('title' => 'Кинде́й Сидский (Памфилийский)','title_genitive' => 'Кинде́я Сидского (Памфилийского)'),
  array('title' => 'Анто́ний Константинопольский','title_genitive' => 'Анто́ния'),
  array('title' => 'Михаил Розов','title_genitive' => 'Михаила <span style="font-size: 10pt;"><em>Розова</em></span>'),
  array('title' => 'Феофа́н Милостивый, Газский','title_genitive' => 'Феофа́на Милостивого'),
  array('title' => 'Илия́ Березовский','title_genitive' => 'Илии́ <span style="font-size: 10pt;"><em>Березовского</em></span>'),
  array('title' => 'Мануи́л Адрианопольский','title_genitive' => 'Мануи́ла'),
  array('title' => 'Алекса́ндр Пиднский','title_genitive' => 'Алекса́ндра Пиднского'),
  array('title' => 'Никола́й Покровский','title_genitive' => 'Никола́я <span style="font-size: 10pt;"><em>Покровского</em></span>'),
  array('title' => 'Трифи́ллий Левкусийский (Кипрский)','title_genitive' => 'Трифи́ллия'),
  array('title' => 'Евдемо́н Фракийский','title_genitive' => 'Евдемо́на Фракийского'),
  array('title' => 'Роман Римский','title_genitive' => 'Романа'),
  array('title' => 'Влади́мир Холодковский','title_genitive' => 'Влади́мира <span style="font-size: 10pt;"><em>Холодковского</em></span>'),
  array('title' => 'По́нтий Римлянин, Кимельский','title_genitive' => 'По́нтия Римлянина'),
  array('title' => 'Иоа́нн Калабухов','title_genitive' => 'Иоа́нна <span style="font-size: 10pt;"><em>Калабухова</em></span>'),
  array('title' => 'Павел Васильевский','title_genitive' => 'Павла <span style="font-size: 10pt;"><em>Васильевского</em></span>'),
  array('title' => 'Николай Караман, Смирнский','title_genitive' => 'Николая Карамана'),
  array('title' => 'Се́ргий Лавров','title_genitive' => 'Се́ргия <span style="font-size: 10pt;"><em>Лаврова</em></span>'),
  array('title' => 'Кирилл Гортинский','title_genitive' => 'Кирилла'),
  array('title' => 'Дамиа́н (Воскресенский), Курский','title_genitive' => 'Дамиа́на <span style="font-size: 10pt;"><em>(Воскресенского)</em></span>'),
  array('title' => 'Софро́ний Кипрский','title_genitive' => 'Софро́ния'),
  array('title' => 'Васи́лий Афинянин, Аполлониадский (Македонский)','title_genitive' => 'Васи́лия'),
  array('title' => 'Тара́сий Глушицкий','title_genitive' => 'Тара́сия Глушицкого'),
  array('title' => 'Фео́дор Византийский','title_genitive' => 'Фео́дора Византийского'),
  array('title' => 'Рафаи́л (Шейченко)','title_genitive' => 'Рафаи́ла <span style="font-size: 10pt;"><em>(Шейченко)</em></span>'),
  array('title' => 'Палла́дий Попов','title_genitive' => 'Палла́дия <span style="font-size: 10pt;"><em>Попова</em></span>'),
  array('title' => 'Андрони́к Аназарвский','title_genitive' => 'Андрони́ка'),
  array('title' => 'Ники́фор Тивериопольский','title_genitive' => 'Ники́фора Тивериопольского'),
  array('title' => 'Петр Косминков','title_genitive' => 'Петра <span style="font-size: 10pt;"><em>Косминкова</em></span>'),
  array('title' => 'Па́вел Коринфский','title_genitive' => 'Па́вла Коринфского'),
  array('title' => 'Константин Любомудров','title_genitive' => 'Константина <span style="font-size: 10pt;"><em>Любомудрова</em></span>'),
  array('title' => 'Иоа́нн Мервский','title_genitive' => 'Иоа́нна Мервского'),
  array('title' => 'Меле́тий (Федюнев)','title_genitive' => 'Меле́тия <span style="font-size: 10pt;"><em>(Федюнева)</em></span>'),
  array('title' => 'Кла́вдий Киликийский','title_genitive' => 'Кла́вдия'),
  array('title' => 'Иу́ст Римский','title_genitive' => 'Иу́ста Римского'),
  array('title' => 'Теле́тий Никомидийский','title_genitive' => 'Теле́тия Никомидийского'),
  array('title' => 'Андрони́к Московский','title_genitive' => 'Андрони́ка'),
  array('title' => 'Влади́мир Сергеев','title_genitive' => 'Влади́мира <span style="font-size: 10pt;"><em>Сергеева</em></span>'),
  array('title' => 'Михаил Белороссов','title_genitive' => 'Михаила <span style="font-size: 10pt;"><em>Белороссова</em></span>'),
  array('title' => 'Ири́ний Египетский','title_genitive' => 'Ири́ния'),
  array('title' => 'Иоа́нн Псковский, затворник','title_genitive' => 'Иоа́нна Псковского'),
  array('title' => 'Варада́т Сирийский, пустынник','title_genitive' => 'Варада́та'),
  array('title' => 'А́вда Кашкарский','title_genitive' => 'А́вды'),
  array('title' => 'Петр Крестов','title_genitive' => 'Петра <span style="font-size: 10pt;"><em>Крестова</em></span>'),
  array('title' => 'Диони́сий Александрийский','title_genitive' => 'Диони́сия Александрийского'),
  array('title' => 'Иу́да Иаковлев (Левве́й, Фадде́й), брат Господень','title_genitive' => 'Иу́ды Иаковлева'),
  array('title' => 'Алекси́й (Бельковский), Великоустюжский','title_genitive' => 'Алекси́я <span style="font-size: 10pt;"><em>(Бельковского)</em></span>'),
  array('title' => 'Варлаа́м Валаамский','title_genitive' => 'Варлаа́ма'),
  array('title' => 'Фавст','title_genitive' => 'Фавста'),
  array('title' => 'Касте́л','title_genitive' => 'Касте́ла'),
  array('title' => 'Симео́н Афонькин','title_genitive' => 'Симео́на <span style="font-size: 10pt;"><em>Афонькина</em></span>'),
  array('title' => 'Николай Аристов','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Аристова</em></span>'),
  array('title' => 'Лео́нтий Строцюк','title_genitive' => 'Лео́нтия <span style="font-size: 10pt;"><em>Строцюка</em></span>'),
  array('title' => 'Серапио́н','title_genitive' => 'Серапио́на'),
  array('title' => 'Дими́трий Ильинский','title_genitive' => 'Дими́трия <span style="font-size: 10pt;"><em>Ильинского</em></span>'),
  array('title' => 'Серапио́н Гареджийский, чудотворец','title_genitive' => 'Серапио́на Гареджийского'),
  array('title' => 'Петр (в иночестве Дави́д) Муромский','title_genitive' => 'Петра́ (в иночестве Дави́да)'),
  array('title' => 'Заха́рия Иерусалимский','title_genitive' => 'Заха́рии'),
  array('title' => 'Иоа́нн Монах, Ефесский','title_genitive' => 'Иоа́нна Монаха'),
  array('title' => 'Ти́грий Константинопольский','title_genitive' => 'Ти́грия'),
  array('title' => 'Серафи́м (Остроумов), Смоленский','title_genitive' => 'Серафи́ма <span style="font-size: 10pt;"><em>(Остроумова)</em></span>'),
  array('title' => 'Гедео́н Серпуховский','title_genitive' => 'Гедео́на Серпуховского'),
  array('title' => 'Роман Марченко','title_genitive' => 'Романа <span style="font-size: 10pt;"><em>Марченко</em></span>'),
  array('title' => 'Фео́дор Едесский','title_genitive' => 'Фео́дора'),
  array('title' => 'Адриа́н Коринфский','title_genitive' => 'Адриа́на Коринфского'),
  array('title' => 'Григо́рий Палама, Солунский (Фессалоникийский)','title_genitive' => 'Григо́рия Паламы'),
  array('title' => 'Максим Римский, епарх','title_genitive' => 'Максима'),
  array('title' => 'Алекси́й Никологорский','title_genitive' => 'Алекси́я <span style="font-size: 10pt;"><em>Никологорского</em></span>'),
  array('title' => 'Плато́н Горных','title_genitive' => 'Плато́на <span style="font-size: 10pt;"><em>Горных</em></span>'),
  array('title' => 'Гене́флий Фракийский','title_genitive' => 'Гене́флия Фракийского'),
  array('title' => 'Влади́мир Хрищенович','title_genitive' => 'Влади́мира <span style="font-size: 10pt;"><em>Хрищеновича</em></span>'),
  array('title' => 'Анто́ний Египетский','title_genitive' => 'Анто́ния'),
  array('title' => 'Елисе́й Лавришевский','title_genitive' => 'Елисе́я Лавришевского'),
  array('title' => 'Андре́й Рублев, иконописец','title_genitive' => 'Андре́я Рублева, иконописца'),
  array('title' => 'Игна́тий Печерский','title_genitive' => 'Игна́тия'),
  array('title' => 'Моде́ст Римский, Пестун','title_genitive' => 'Моде́ста'),
  array('title' => 'Маро́н Сирийский, пустынник','title_genitive' => 'Маро́на, пустынника Сирийского'),
  array('title' => 'Иоаса́ф Индийский, царевич','title_genitive' => 'Иоаса́фа'),
  array('title' => 'Васи́лий Протопопов','title_genitive' => 'Васи́лия <span style="font-size: 10pt;"><em>Протопопова</em></span>'),
  array('title' => 'Довмо́нт (в Крещении Тимофе́й) Псковский','title_genitive' => 'Довмо́нта, во Святом Крещении Тимофе́я, Псковского'),
  array('title' => 'Руф Дамасский','title_genitive' => 'Руфа Дамасского'),
  array('title' => 'Завуло́н Каппадокийский','title_genitive' => 'Завуло́на'),
  array('title' => 'Иасо́н Римский','title_genitive' => 'Иасо́на'),
  array('title' => 'Протоге́н Каррийский','title_genitive' => 'Протоге́на исп.'),
  array('title' => 'Ианнуа́рий Соловецкий','title_genitive' => 'Ианнуа́рия Соловецкого'),
  array('title' => 'Михаил Архангел, Архистратиг','title_genitive' => 'Михаила'),
  array('title' => 'Диони́сий Пергийский (Памфилийский)','title_genitive' => 'Диони́сия'),
  array('title' => 'Сильве́стр Валаамский','title_genitive' => 'Сильве́стра'),
  array('title' => 'Азада́н Персидский','title_genitive' => 'Азада́на'),
  array('title' => 'Михаи́л Строев','title_genitive' => 'Михаи́ла <span style="font-size: 10pt;"><em>Строева</em></span>'),
  array('title' => 'Афинодо́р Египетский','title_genitive' => 'Афинодо́ра Египетского'),
  array('title' => 'Вил Сирийский','title_genitive' => 'Ви́ла'),
  array('title' => 'Севи́р Фракийский','title_genitive' => 'Севи́ра'),
  array('title' => 'Иоа́нн (Мавия), царь Персидский','title_genitive' => 'Иоа́нна'),
  array('title' => 'Галактио́н Вологодский, затворник','title_genitive' => 'Галактио́на Вологодского'),
  array('title' => 'Се́ргий (Букашкин)','title_genitive' => 'Се́ргия <span style="font-size: 10pt;"><em>(Букашкина)</em></span>'),
  array('title' => 'Влади́мир (Загреба)','title_genitive' => 'Влади́мира <span style="font-size: 10pt;"><em>(Загребы)</em></span>'),
  array('title' => 'Афроди́сий Киликийский','title_genitive' => 'Афроди́сия Киликийского'),
  array('title' => 'Иоа́нн Адрианопольский','title_genitive' => 'Иоа́нна'),
  array('title' => 'Ви́ктор (Островидов), Глазовский','title_genitive' => 'Ви́ктора <span style="font-size: 10pt;"><em>(Островидова)</em></span>, исп.'),
  array('title' => 'Ага́пий Ватопедский (Афонский)','title_genitive' => 'Ага́пия Ватопедского'),
  array('title' => 'Максим Московский, Христа ради юродивый','title_genitive' => 'Максима, Христа ради юродивого, Московского чудотворца'),
  array('title' => 'Куто́ний Римский','title_genitive' => 'Куто́ния'),
  array('title' => 'Фадде́й Степанцминдский','title_genitive' => 'Фадде́я Степанцминдского'),
  array('title' => 'Па́пий Пергийский (Памфилийский)','title_genitive' => 'Па́пия'),
  array('title' => 'Варна́ва Ветлужский','title_genitive' => 'Варна́вы Ветлужского'),
  array('title' => 'Христофо́р Савваит','title_genitive' => 'Христофо́ра Савваита'),
  array('title' => 'Еро́с Паремвольский','title_genitive' => 'Еро́са'),
  array('title' => 'Феофа́н Перифеорийский','title_genitive' => 'Феофа́на'),
  array('title' => 'Симео́н Мироточивый (в миру Стефа́н Неманя), Хилендарский (Афонский)','title_genitive' => 'Симео́на Мироточивого, в миру Стефа́на Неманя'),
  array('title' => 'Се́ргий Галин','title_genitive' => 'Се́ргия <span style="font-size: 10pt;"><em>Галина</em></span>'),
  array('title' => 'Ла́зарь Персидский','title_genitive' => 'Ла́заря Персидского'),
  array('title' => 'Ки́фа Иконийский (Колофонский)','title_genitive' => 'Ки́фы'),
  array('title' => 'Николай Подьяков','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Подьякова</em></span>'),
  array('title' => 'Ианики́т (Аники́та) Никопольский (Армянский)','title_genitive' => 'Ианики́та'),
  array('title' => 'Зои́л','title_genitive' => 'Зои́ла'),
  array('title' => 'Ио́сиф Хиосский','title_genitive' => 'Ио́сифа Хиосского'),
  array('title' => 'Максим Маркианопольский (Мизийский)','title_genitive' => 'Максима'),
  array('title' => 'Се́ргий Уклонский','title_genitive' => 'Се́ргия <span style="font-size: 10pt;"><em>Уклонского</em></span>'),
  array('title' => 'Капито́н Оливрийский (Константинопольский)','title_genitive' => 'Капито́на'),
  array('title' => 'Антипа́тр Бострийский','title_genitive' => 'Антипа́тра'),
  array('title' => 'Николай Житов','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Житова</em></span>'),
  array('title' => 'Порфи́рий Колосовский','title_genitive' => 'Порфи́рия <span style="font-size: 10pt;"><em>Колосовского</em></span>'),
  array('title' => 'Иоа́нн Печерский, Киевский, отрок, первомученик Российский','title_genitive' => 'Иоа́нна Печерского, в Киеве'),
  array('title' => 'Афр Египетский','title_genitive' => 'А́фра'),
  array('title' => 'Сарви́л Сирийский','title_genitive' => 'Сарви́ла'),
  array('title' => 'Максим Антиохийский','title_genitive' => 'Максима'),
  array('title' => 'Ге́рман Валаамский','title_genitive' => 'Ге́рмана'),
  array('title' => 'Петр Афонский','title_genitive' => 'Петра Афонского'),
  array('title' => 'Евге́ний Антиохийский, Мавританский','title_genitive' => 'Евге́ния'),
  array('title' => 'Крисп Эгинский','title_genitive' => 'Криспа'),
  array('title' => 'Константин Михайловский','title_genitive' => 'Константина <span style="font-size: 10pt;"><em>Михайловского</em></span>'),
  array('title' => 'Панагио́т Кесарийский','title_genitive' => 'Панагио́та Кесарийского'),
  array('title' => 'Елла́дий Восточный','title_genitive' => 'Елла́дия'),
  array('title' => 'Петр Вязников','title_genitive' => 'Петра <span style="font-size: 10pt;"><em>Вязникова</em></span>'),
  array('title' => 'Ростисла́в Великоморавский, князь','title_genitive' => 'Ростисла́ва, князя Великоморавского'),
  array('title' => 'Ио́сиф (Джандиери) Грузинский, чудотворец','title_genitive' => 'Ио́сифа (Джандиери)'),
  array('title' => 'Вита́лий Римлянин','title_genitive' => 'Вита́лия'),
  array('title' => 'Ака́кий Прусский (Вифинский)','title_genitive' => 'Ака́кия'),
  array('title' => 'Маркиа́н Сиракузский (Маркелл Сикелийский)','title_genitive' => 'Маркиа́на'),
  array('title' => 'Иувена́лий (Ювена́лий) Иерусалимский','title_genitive' => 'Иувена́лия (Ювена́лия)'),
  array('title' => 'Николай Копнинский','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Копнинского</em></span>'),
  array('title' => 'Васи́лий Спасский','title_genitive' => 'Васи́лия <span style="font-size: 10pt;"><em>Спасского</em></span>'),
  array('title' => 'Патерму́фий Тирский','title_genitive' => 'Патерму́фия'),
  array('title' => 'Ви́ктор Дамасский','title_genitive' => 'Ви́ктора'),
  array('title' => 'Фома́ Константинопольский','title_genitive' => 'Фомы́ Константинопольского'),
  array('title' => 'Евно́ик Севастийский','title_genitive' => 'Евно́ика'),
  array('title' => 'Кли́мент Анкирский, Многострадальный','title_genitive' => 'Кли́мента'),
  array('title' => 'Петр Никейский','title_genitive' => 'Петра'),
  array('title' => 'Ка́стул Римский','title_genitive' => 'Ка́стула'),
  array('title' => 'Евсе́вий Лаодикийский','title_genitive' => 'Евсе́вия'),
  array('title' => 'Арте́мий Веркольский, отрок','title_genitive' => 'отрока Арте́мия Веркольского'),
  array('title' => 'Алекса́ндр Чекалов','title_genitive' => 'Алекса́ндра <span style="font-size: 10pt;"><em>Чекалова</em></span>'),
  array('title' => 'Инноке́нтий (Борисов), Херсонский','title_genitive' => 'Инноке́нтия (Борисова)'),
  array('title' => 'Николай Мечевский, Триккальский','title_genitive' => 'Николая (из Мечева)'),
  array('title' => 'Афана́сий Муромский (Мурманский), Олонецкий','title_genitive' => 'Афана́сия (XV)'),
  array('title' => 'Николай Виноградов','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Виноградова</em></span>'),
  array('title' => 'Петр Озерецковский','title_genitive' => 'Петра <span style="font-size: 10pt;"><em>Озерецковского</em></span>'),
  array('title' => 'Сави́н Фракийский','title_genitive' => 'Сави́на Фракийского'),
  array('title' => 'Рин Фракийский','title_genitive' => 'Рина Фракийского'),
  array('title' => 'Феофа́н Исповедник, Сигрианский, Летописец','title_genitive' => 'Феофа́на исп., Сигрианского'),
  array('title' => 'Дий','title_genitive' => 'Ди́я'),
  array('title' => 'Диони́сий Кесарийский (Палестинский)','title_genitive' => 'Диони́сия'),
  array('title' => 'Иоаса́ф (Крымзин)','title_genitive' => 'Иоаса́фа <span style="font-size: 10pt;"><em>(Крымзина)</em></span>'),
  array('title' => 'Варна́ва Гефсиманский (Меркулов)','title_genitive' => 'Варна́вы Гефсиманского (Меркулова)'),
  array('title' => 'Михаил Некрасов','title_genitive' => 'Михаила <span style="font-size: 10pt;"><em>Некрасова</em></span>'),
  array('title' => 'Алекса́ндр Минервин','title_genitive' => 'Алекса́ндра <span style="font-size: 10pt;"><em>Минервина</em></span>'),
  array('title' => 'Ио́сиф Заоникиевский (Вологодский), Христа ради юродивый','title_genitive' => 'Ио́сифа Заоникиевского (Вологодского)'),
  array('title' => 'Иоа́нн Василевский','title_genitive' => 'Иоа́нна <span style="font-size: 10pt;"><em>Василевского</em></span>'),
  array('title' => 'Фео́фил Оксиринфский (Египетский)','title_genitive' => 'Фео́фила'),
  array('title' => 'Диодо́р Римский','title_genitive' => 'Диодо́ра'),
  array('title' => 'Николай Ковалев','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Ковалева</em></span>'),
  array('title' => 'Ана́ния Новгородский, иконописец','title_genitive' => 'Ана́нии Новгородского'),
  array('title' => 'Влади́мир Дмитриевский','title_genitive' => 'Влади́мира <span style="font-size: 10pt;"><em>Дмитриевского</em></span>'),
  array('title' => 'Стефа́н Хитров','title_genitive' => 'Стефа́на <span style="font-size: 10pt;"><em>Хитрова</em></span>'),
  array('title' => 'Авуди́м Тенедосский','title_genitive' => 'Авуди́ма Тенедосского'),
  array('title' => 'Мо́лий Фракийский','title_genitive' => 'Мо́лия Фракийского'),
  array('title' => 'Евтро́пий Амасийский','title_genitive' => 'Евтро́пия'),
  array('title' => 'Мени́гн','title_genitive' => 'Мени́гна'),
  array('title' => 'Алекса́ндр Тивериадский','title_genitive' => 'Алекса́ндра Тивериадского'),
  array('title' => 'Ила́рий Калиптский','title_genitive' => 'Ила́рия'),
  array('title' => 'Лука́ Тавроменийский','title_genitive' => 'Луки́ Тавроменийского'),
  array('title' => 'Лавре́нтий Печерский, затворник','title_genitive' => 'Лавре́нтия затворника'),
  array('title' => 'Влади́мир Сперанский','title_genitive' => 'Влади́мира <span style="font-size: 10pt;"><em>Сперанского</em></span>'),
  array('title' => 'Капито́н','title_genitive' => 'Капито́на'),
  array('title' => 'Никита Печерский, Новгородский, затворник','title_genitive' => 'Никиты, затворника Печерского'),
  array('title' => 'Афана́сий Севастийский','title_genitive' => 'Афана́сия'),
  array('title' => 'Рафаи́л (Тюпин)','title_genitive' => 'Рафаи́ла <span style="font-size: 10pt;"><em>(Тюпина)</em></span>'),
  array('title' => 'Никано́р (Морозкин)','title_genitive' => 'Никано́ра <span style="font-size: 10pt;"><em>(Морозкина)</em></span>'),
  array('title' => 'Адриа́н Ванейский, Кесарийский (Палестинский)','title_genitive' => 'Адриа́на'),
  array('title' => 'Евфроси́н Синозерский, Новгородский','title_genitive' => 'Евфроси́на Синозерского, Новгородского'),
  array('title' => 'Иеремии́л, Архангел','title_genitive' => 'Иеремии́ла'),
  array('title' => 'А́вель, сын Ада́ма','title_genitive' => 'А́веля, сына Ада́ма'),
  array('title' => 'Вячесла́в Закедский','title_genitive' => 'Вячесла́ва <span style="font-size: 10pt;"><em>Закедского</em></span>'),
  array('title' => 'Григо́рий Омиритский','title_genitive' => 'Григо́рия'),
  array('title' => 'Ло́нгин Коряжемский','title_genitive' => 'Ло́нгина Коряжемского'),
  array('title' => 'Алекси́й Смирнов','title_genitive' => 'Алекси́я <span style="font-size: 10pt;"><em>Смирнова</em></span>'),
  array('title' => 'Иоа́нн Пьянков','title_genitive' => 'Иоа́нна <span style="font-size: 10pt;"><em>Пьянкова</em></span>'),
  array('title' => 'Гео́ргий Новгородский, Христа ради юродивый','title_genitive' => 'Гео́ргия Новгородского, Христа ради юродивого'),
  array('title' => 'Септе́мин Ликаонский','title_genitive' => 'Септе́мина'),
  array('title' => 'Феости́х Кизический','title_genitive' => 'Феости́ха'),
  array('title' => 'Фео́дор Освященный','title_genitive' => 'Фео́дора Освященного'),
  array('title' => 'Васи́лий Анкирский, Кесарийский','title_genitive' => 'Васи́лия Анкирского'),
  array('title' => 'Фал (Фалес)','title_genitive' => 'Фала'),
  array('title' => 'Геро́нтий Московский и всея Руси','title_genitive' => 'Геро́нтия'),
  array('title' => 'Филаде́льф Бастийский, Месопольский','title_genitive' => 'Филаде́льфа'),
  array('title' => 'Плато́н Анкирский','title_genitive' => 'Плато́на Анкирского'),
  array('title' => 'Корни́лий Удилович','title_genitive' => 'Корни́лия <span style="font-size: 10pt;"><em>Удиловича</em></span>'),
  array('title' => 'Се́ргий Крестников','title_genitive' => 'Се́ргия <span style="font-size: 10pt;"><em>Крестникова</em></span>'),
  array('title' => 'Або́ Тбилисский','title_genitive' => 'Або́ Тбилисского'),
  array('title' => 'Глеб (в Крещении Дави́д), страстотерпец','title_genitive' => 'Гле́ба'),
  array('title' => 'Досифе́й Верхнеостровский, Псковский','title_genitive' => 'Досифе́я Верхнеостровского, Псковского'),
  array('title' => 'Николай Ершов','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Ершова</em></span>'),
  array('title' => 'Марти́рий Константинопольский','title_genitive' => 'Марти́рия'),
  array('title' => 'Николай Бельтюков','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Бельтюкова</em></span>'),
  array('title' => 'Ники́фор (Югов)','title_genitive' => 'Ники́фора (Югова)'),
  array('title' => 'Афана́сий Печерский, затворник','title_genitive' => 'Афана́сия, затворника Печерского, в Ближних пещерах'),
  array('title' => 'Нарса (Нарси́н) Персидский','title_genitive' => 'Нарсы (Нарси́на) Персидского'),
  array('title' => 'Все́волод Смирнов','title_genitive' => 'Все́волода <span style="font-size: 10pt;"><em>Смирнова</em></span>'),
  array('title' => 'Евфи́мий (Кереселидзе)','title_genitive' => 'Евфи́мия (Кереселидзе)'),
  array('title' => 'Васи́лий (Зеленцов), Прилукский','title_genitive' => 'Васи́лия <span style="font-size: 10pt;"><em>(Зеленцова)</em></span>'),
  array('title' => 'Севериа́н Севастийский','title_genitive' => 'Севериа́на'),
  array('title' => 'Ника́ндр Египетский, воин','title_genitive' => 'Ника́ндра'),
  array('title' => 'Влади́мир Проферансов','title_genitive' => 'Влади́мира <span style="font-size: 10pt;"><em>Проферансова</em></span>'),
  array('title' => 'Феокти́ст Хоперсков','title_genitive' => 'Феокти́ста <span style="font-size: 10pt;"><em>Хоперскова</em></span>'),
  array('title' => 'Константин Косинский, Старорусский','title_genitive' => 'Константина'),
  array('title' => 'Инноке́нтий (Кульчицкий), Иркутский','title_genitive' => 'Инноке́нтия (Кульчицкого)'),
  array('title' => 'Ефе́рий','title_genitive' => 'Ефе́рия'),
  array('title' => 'Иоа́нн Рудинский','title_genitive' => 'Иоа́нна <span style="font-size: 10pt;"><em>Рудинского</em></span>'),
  array('title' => 'Асте́рий Римлянин','title_genitive' => 'Асте́рия'),
  array('title' => 'Никола́й (Велимирович), Сербский, Охридский и Жичский','title_genitive' => 'Никола́я (Велимировича)'),
  array('title' => 'Павел Гайдай','title_genitive' => 'Павла <span style="font-size: 10pt;"><em>Гайдая</em></span>'),
  array('title' => 'Париго́рий Патарский','title_genitive' => 'Париго́рия Патарского'),
  array('title' => 'Дамиа́н Аравийский, Киликийский, бессребреник','title_genitive' => 'Дамиа́на'),
  array('title' => 'Са́вва Освященный, Муталаскский','title_genitive' => 'Са́ввы Освященного'),
  array('title' => 'Феодо́сий Сирмийский','title_genitive' => 'Феодо́сия'),
  array('title' => 'Фанти́н Солунский (Фессалоникийский)','title_genitive' => 'Фанти́на чудотворца, в Солуни'),
  array('title' => 'Фео́дор Васильевич Острожский, Печерский, князь','title_genitive' => 'Фео́дора'),
  array('title' => 'Кассиа́н Комельский','title_genitive' => 'Кассиа́на'),
  array('title' => 'Фео́дор Кандавлский, Никомидийский','title_genitive' => 'Фео́дора'),
  array('title' => 'Анто́ний Великий, Египетский','title_genitive' => 'Анто́ния Великого'),
  array('title' => 'Ростисла́в (в Крещении Михаи́л) Мстиславич Киевский, Смоленский','title_genitive' => 'Ростисла́ва (в Крещении Михаи́ла) Мстиславича Киевского'),
  array('title' => 'И́ов Зографский (Афонский)','title_genitive' => 'И́ова'),
  array('title' => 'Ви́ктор Никомидийский','title_genitive' => 'Ви́ктора'),
  array('title' => 'Христофо́р Никомидийский','title_genitive' => 'Христофо́ра'),
  array('title' => 'Фе́ликс (Фили́к) Терракинский','title_genitive' => 'Фе́ликса'),
  array('title' => 'Се́ргий Астахов','title_genitive' => 'Се́ргия <span style="font-size: 10pt;"><em>Астахова</em></span>'),
  array('title' => 'Сели́ний (Селиниа́с) Египетский','title_genitive' => 'Сели́ния'),
  array('title' => 'Иера́кс Египетский, пустынник','title_genitive' => 'Иера́кса Египетского'),
  array('title' => 'Иа́ков Костурский, Дохиарский (Афонский)','title_genitive' => 'Иа́кова'),
  array('title' => 'Лукиа́н Месукевийский, Грузинский','title_genitive' => 'Лукиа́на'),
  array('title' => 'Григо́рий Византийский, Афонский','title_genitive' => 'Григо́рия Византийского'),
  array('title' => 'Ирине́й Сирмийский (Сремский), Сербский','title_genitive' => 'Ирине́я'),
  array('title' => 'Дамиа́н Сирийский, пустынник','title_genitive' => 'Дамиа́на'),
  array('title' => 'Да́сий Никомидийский','title_genitive' => 'Да́сия'),
  array('title' => 'Фео́фил Никомидийский','title_genitive' => 'Фео́фила'),
  array('title' => 'Петр I Александрийский','title_genitive' => 'Петра I Александрийского'),
  array('title' => 'Иоа́нн Египетский, пустынник','title_genitive' => 'Иоа́нна Египетского, пустынника'),
  array('title' => 'Дави́д Грузинский','title_genitive' => 'Дави́да'),
  array('title' => 'Андрони́к (Никольский), Пермский','title_genitive' => 'Андрони́ка <span style="font-size: 10pt;"><em>(Никольского)</em></span>'),
  array('title' => 'Иоа́нн Артоболевский','title_genitive' => 'Иоа́нна <span style="font-size: 10pt;"><em>Артоболевского</em></span>'),
  array('title' => 'Роман Кесарийский, Антиохийский','title_genitive' => 'Романа'),
  array('title' => 'Анато́лий Рождественский','title_genitive' => 'Анато́лия <span style="font-size: 10pt;"><em>Рождественского</em></span>'),
  array('title' => 'Ера́зм Формийский (Кампанийский)','title_genitive' => 'Ера́зма'),
  array('title' => 'Диони́сий Фракийский','title_genitive' => 'Диони́сия'),
  array('title' => 'Фадде́й Студит','title_genitive' => 'Фадде́я Студита'),
  array('title' => 'Амфило́хий Почаевский (Головатюк)','title_genitive' => 'Амфило́хия Почаевского (Головатюка)'),
  array('title' => 'Филл Готфский','title_genitive' => 'Фи́лла'),
  array('title' => 'Ге́рман (Косолапов), Вольский','title_genitive' => 'Ге́рмана <span style="font-size: 10pt;"><em>(Косолапова)</em></span>'),
  array('title' => 'Влади́мир Талюш','title_genitive' => 'Влади́мира Талюша'),
  array('title' => 'Максимиа́н Мелитинский','title_genitive' => 'Максимиа́на'),
  array('title' => 'Дими́трий Спасский','title_genitive' => 'Дими́трия <span style="font-size: 10pt;"><em>Спасского</em></span>'),
  array('title' => 'Иса́ия Египтянин, Кесарийский (Палестинский)','title_genitive' => 'Иса́ии'),
  array('title' => 'Ио́на Персидский','title_genitive' => 'Ио́ны'),
  array('title' => 'Пи́мен Угрешский (Мясников)','title_genitive' => 'Пи́мена Угрешского'),
  array('title' => 'Иоаса́ф Зографский (Афонский)','title_genitive' => 'Иоаса́фа'),
  array('title' => 'Ге́рман Белозерский','title_genitive' => 'Ге́рмана Белозерского'),
  array('title' => 'Не́стор Солунский (Фессалоникийский)','title_genitive' => 'Не́стора Солунского (Фессалоникийского)'),
  array('title' => 'Тара́сий Константинопольский','title_genitive' => 'Тара́сия'),
  array('title' => 'Афана́сий Мидикийский','title_genitive' => 'Афана́сия Мидикийского'),
  array('title' => 'Павли́н Афинянин','title_genitive' => 'Павли́на'),
  array('title' => 'Евфи́мий Новый, Святогорец, Иверский (Афонский)','title_genitive' => 'Евфи́мия Иверского, Святогорца'),
  array('title' => 'Андре́й Бенедиктов','title_genitive' => 'Андре́я <span style="font-size: 10pt;"><em>Бенедиктова</em></span>'),
  array('title' => 'Стефа́н Византийский','title_genitive' => 'Стефа́на'),
  array('title' => 'Иулиа́н Кеноманийский','title_genitive' => 'Иулиа́на'),
  array('title' => 'Асте́рий Синклитик, Кесарийский (Палестинский)','title_genitive' => 'Асте́рия'),
  array('title' => 'Иоа́нн Бороздин','title_genitive' => 'Иоа́нна <span style="font-size: 10pt;"><em>Бороздина</em></span>'),
  array('title' => 'Алекса́ндр Римский','title_genitive' => 'Алекса́ндра Римского'),
  array('title' => 'Никита Халкидонский','title_genitive' => 'Никиты исп.'),
  array('title' => 'Николай Студийский','title_genitive' => 'Николая'),
  array('title' => 'Маг волхв','title_genitive' => 'Мага волхва'),
  array('title' => 'Феоду́л Солунский (Фессалоникийский)','title_genitive' => 'Феоду́ла'),
  array('title' => 'Васи́лий Давыдович Ярославский','title_genitive' => 'Васи́лия Давыдовича Ярославского'),
  array('title' => 'Алекса́ндр Сахаров','title_genitive' => 'Алекса́ндра <span style="font-size: 10pt;"><em>Сахарова</em></span>'),
  array('title' => 'Евти́хий (Качур)','title_genitive' => 'Евти́хия <span style="font-size: 10pt;"><em>(Качура)</em></span>'),
  array('title' => 'Гео́ргий Тимофеев','title_genitive' => 'Гео́ргия <span style="font-size: 10pt;"><em>Тимофеева</em></span>'),
  array('title' => 'Диони́сий Коринфский','title_genitive' => 'Диони́сия'),
  array('title' => 'Иоа́нн Критский','title_genitive' => 'Иоа́нна Критского'),
  array('title' => 'Ви́ктор Месукевийский, Грузинский','title_genitive' => 'Ви́ктора'),
  array('title' => 'Дими́трий Пелопонесский, Трипольский','title_genitive' => 'Дими́трия Пелопонесского'),
  array('title' => 'Таврио́н (Толоконцев)','title_genitive' => 'Таврио́на <span style="font-size: 10pt;"><em>(Толоконцева)</em></span>'),
  array('title' => 'Аммо́н (Амму́н) Нитрийский, Египетский','title_genitive' => 'Аммо́на (Амму́на) Нитрийского'),
  array('title' => 'Ви́ктор Фракийский','title_genitive' => 'Ви́ктора Фракийского'),
  array('title' => 'Пирр Бретский','title_genitive' => 'Пирра Бретского'),
  array('title' => 'Херимо́н Египетский','title_genitive' => 'Херимо́на Египетского'),
  array('title' => 'Михаил Афинский, садовник','title_genitive' => 'Михаила'),
  array('title' => 'Маркиа́н Константинопольский','title_genitive' => 'Маркиа́на'),
  array('title' => 'Дави́д Гареджийский','title_genitive' => 'Дави́да Гареджийского'),
  array('title' => 'Мари́н Персиянин, Римский','title_genitive' => 'Мари́на'),
  array('title' => 'Петр (Мамонтов)','title_genitive' => 'Петра <span style="font-size: 10pt;"><em>(Мамонтова)</em></span>'),
  array('title' => 'Анто́ний (Арапов), Белогорский','title_genitive' => 'Анто́ния <span style="font-size: 10pt;"><em>(Арапова)</em></span>'),
  array('title' => 'Крони́д (Любимов)','title_genitive' => 'Крони́да <span style="font-size: 10pt;"><em>(Любимова)</em></span>'),
  array('title' => 'Дании́л Алферов','title_genitive' => 'Дании́ла <span style="font-size: 10pt;"><em>Алферова</em></span>'),
  array('title' => 'Анто́ний Виленский (Литовский)','title_genitive' => 'Анто́ния'),
  array('title' => 'Пу́плий Афинский','title_genitive' => 'Пу́плия Афинского'),
  array('title' => 'Горго́ний Севастийский','title_genitive' => 'Горго́ния'),
  array('title' => 'Михе́й Радонежский','title_genitive' => 'Михе́я Радонежского'),
  array('title' => 'Николай Кузьмин','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Кузьмина</em></span>'),
  array('title' => 'Иларио́н Соловьев','title_genitive' => 'Иларио́на <span style="font-size: 10pt;"><em>Соловьева</em></span>'),
  array('title' => 'Ира́клий Афинянин','title_genitive' => 'Ира́клия'),
  array('title' => 'Дании́л Скитский','title_genitive' => 'Дании́ла Скитского'),
  array('title' => 'Ни́кон Сухой, Печерский','title_genitive' => 'Ни́кона Сухого, Печерского, в Ближних пещерах'),
  array('title' => 'Игна́тий Богоносец, Антиохийский','title_genitive' => 'Игна́тия Богоносца'),
  array('title' => 'Влади́мир Рясенский','title_genitive' => 'Влади́мира <span style="font-size: 10pt;"><em>Рясенского</em></span>'),
  array('title' => 'Алекса́ндр Ерошов','title_genitive' => 'Алекса́ндра <span style="font-size: 10pt;"><em>Ерошова</em></span>'),
  array('title' => 'Варлаа́м Чикойский, пустынник','title_genitive' => 'Варлаа́ма'),
  array('title' => 'Петр Атройский','title_genitive' => 'Петра в Атрое'),
  array('title' => 'Симео́н Столпник, Дивногорец, Младший','title_genitive' => 'Симео́на Столпника на Дивной горе'),
  array('title' => 'Вячесла́в Чешский','title_genitive' => 'Вячесла́ва Чешского'),
  array('title' => 'Ри́мма Новодунский, Славянин','title_genitive' => 'Ри́ммы'),
  array('title' => 'Гермоге́н (Боярышнев), Белогорский','title_genitive' => 'Гермоге́на <span style="font-size: 10pt;"><em>(Боярышнева)</em></span>'),
  array('title' => 'Лин','title_genitive' => 'Лина'),
  array('title' => 'Иоа́нн Калинин','title_genitive' => 'Иоа́нна Оленевского <span style="font-size: 10pt;"><em>(Калинина)</em></span> (1951)'),
  array('title' => 'Три́фон Родонежский','title_genitive' => 'Три́фона <span style="font-size: 10pt;"><em>Родонежского</em></span>'),
  array('title' => 'Елевфе́рий Парижский','title_genitive' => 'Елевфе́рия'),
  array('title' => 'Николай Филиппов','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Филиппова</em></span>'),
  array('title' => 'Ника́ндр Мирский','title_genitive' => 'Ника́ндра'),
  array('title' => 'Иереми́я Печерский, Прозорливый','title_genitive' => 'Иереми́и'),
  array('title' => 'Илия́ Египетский, пустынник','title_genitive' => 'Илии́ Египетского'),
  array('title' => 'Евгра́ф Плетнев','title_genitive' => 'Евгра́фа <span style="font-size: 10pt;"><em>Плетнева</em></span>'),
  array('title' => 'Амони́т Мелитинский','title_genitive' => 'Амони́та'),
  array('title' => 'Иоа́нн Пещерник, иже в странах Вавилонских','title_genitive' => 'Иоа́нна Пещерника'),
  array('title' => 'Андре́й Вишерский','title_genitive' => 'Андре́я'),
  array('title' => 'Максим Киевский и Владимирский','title_genitive' => 'Максима Киевского и Владимирского'),
  array('title' => 'Андре́й Первозванный','title_genitive' => 'Андре́я Первозванного'),
  array('title' => 'Феодо́сий I Великий, император','title_genitive' => 'Феодо́сия I Великого'),
  array('title' => 'Маркиа́н Константинопольский','title_genitive' => 'Маркиа́на Константинопольского'),
  array('title' => 'Михе́й Морасфитянин','title_genitive' => 'Михе́я'),
  array('title' => 'Антони́н Сирийский, пустынник','title_genitive' => 'Антони́на'),
  array('title' => 'Се́ргий Римлянин, Росафский','title_genitive' => 'Се́ргия'),
  array('title' => 'Алекса́ндр Органов','title_genitive' => 'Алекса́ндра <span style="font-size: 10pt;"><em>Органова</em></span>'),
  array('title' => 'Алекси́й Знаменский','title_genitive' => 'Алекси́я <span style="font-size: 10pt;"><em>Знаменского</em></span>'),
  array('title' => 'Неа́дий Чудотворец, Митиленский','title_genitive' => 'Неа́дия Чудотворец'),
  array('title' => 'Тимофе́й Мавританский','title_genitive' => 'Тимофе́я'),
  array('title' => 'Алекси́й Великосельский','title_genitive' => 'Алекси́я <span style="font-size: 10pt;"><em>Великосельского</em></span>'),
  array('title' => 'Ка́стор','title_genitive' => 'Ка́стора'),
  array('title' => 'Силуа́н Солунский (Фессалоникийский)','title_genitive' => 'Силуа́на'),
  array('title' => 'Зино́н Скитский, чудотворец','title_genitive' => 'Зино́на Скитского'),
  array('title' => 'Ко́нон Палестинский','title_genitive' => 'Ко́нона Палестинского'),
  array('title' => 'Николай Пятницкий','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Пятницкого</em></span>'),
  array('title' => 'Иоа́нн (Варсоно́фий) Дамасский, Нитрийский, отшельник','title_genitive' => 'Иоа́нна, нареченного Варсоно́фием'),
  array('title' => 'Страто́н Фракийский','title_genitive' => 'Страто́на Фракийского'),
  array('title' => 'Проко́пий Варненский, Смирнский','title_genitive' => 'Проко́пия Смирнского'),
  array('title' => 'Фео́дор Ростиславич Черный, Смоленский, Ярославский','title_genitive' => 'Фео́дора Ростиславича Черного, Смоленского'),
  array('title' => 'Марке́лл','title_genitive' => 'Марке́лла'),
  array('title' => 'Евелпи́ст Римский','title_genitive' => 'Евелпи́ста'),
  array('title' => 'Андрони́к Паннонийский','title_genitive' => 'Андрони́ка'),
  array('title' => 'Михаил Твердовский','title_genitive' => 'Михаила <span style="font-size: 10pt;"><em>Твердовского</em></span>'),
  array('title' => 'Васс Никомидийский','title_genitive' => 'Ва́сса'),
  array('title' => 'Лев Великий, Макелла, император','title_genitive' => 'Льва Великого'),
  array('title' => 'Анто́ний Вологодский, Великопермский','title_genitive' => 'Анто́ния Вологодского, Великопермского'),
  array('title' => 'Ане́кт Кесарийский','title_genitive' => 'Ане́кта Кесарийского'),
  array('title' => 'Михаил Борисов','title_genitive' => 'Михаила <span style="font-size: 10pt;"><em>Борисова</em></span>'),
  array('title' => 'Фео́дор Африканский','title_genitive' => 'Фео́дора и иных 33-х'),
  array('title' => 'Андре́й Лампсакский','title_genitive' => 'Андре́я'),
  array('title' => 'Ме́ртий','title_genitive' => 'Ме́ртия'),
  array('title' => 'Они́сим','title_genitive' => 'Они́сима'),
  array('title' => 'Евпо́р Критский','title_genitive' => 'Евпо́ра'),
  array('title' => 'Николай Никольский','title_genitive' => 'Николая <span style="font-size: 10pt;"><em>Никольского</em></span>'),
  array('title' => 'Дими́трий Вознесенский','title_genitive' => 'Дими́трия <span style="font-size: 10pt;"><em>Вознесенского</em></span>'),
  array('title' => 'Гу́рий Казанский','title_genitive' => 'Гу́рия'),
  array('title' => 'Лоллио́н старший','title_genitive' => 'Лоллио́на старшего'),
  array('title' => 'Ле́вкий Кесарийский (Вифинский)','title_genitive' => 'Ле́вкия'),
  array('title' => 'Евсто́хий','title_genitive' => 'Евсто́хия'),
  array('title' => 'Макарий Мелитинский','title_genitive' => 'Макария'),
  array('title' => 'Пио́ний Смирнский','title_genitive' => 'Пио́ния'),
  array('title' => 'Симео́н Новый Богослов','title_genitive' => 'Симео́на Нового Богослова'),
  array('title' => 'Ти́хон (Беллавин) Московский и всея России','title_genitive' => 'Ти́хона'),

);
